# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B compile --file pom.xml
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B test --file pom.xml
  send_status:
    runs-on: [ubuntu-latest]
    steps:
      - name: Create Github Deployment Status
        uses: unacast/actions-github-deployment-status@0.2
        with:
          # The GITHUB_TOKEN secret
          github_token: 6d5cddd5d67b18cb439118189aa0a14dfe4732c0
          # The status to create. Can be one of error, failure, inactive, in_progress, queued pending, or success
          status: success
  
    
